=== orangeStas/WebProjectWithXML/src/resources/Devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://127.0.0.1/device"
        xmlns:computers = "http://127.0.0.1/device" >
  <element name="computers" type="computers:devicesType"/>

  <complexType name="devicesType">
    <sequence>
      <element type="computers:computerType" name="computer" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <complexType name="computerType">
    <sequence>
      <element type="computers:typeType" name="type"/>
      <element type="boolean" name="critical"/>
    </sequence>

    <attribute type="ID" name="id" use="required"/>
    <attribute type="string" name="name" use="required"/>

    <attribute name="origin" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[A-z]+"/>
        </restriction>
      </simpleType>
    </attribute>

    <attribute type="positiveInteger" name="price" default="1"/>
  </complexType>

  <complexType name="typeType">
    <sequence>
      <element type="boolean" name="peripheral"/>
      <element type="positiveInteger" name="power"/>
      <element type="computers:hardwareType" name="hardware"/>
      <element type="computers:portsType" name="ports"/>
    </sequence>
  </complexType>

  <simpleType name="portsType">
    <list itemType="computers:portsEnum"/>
  </simpleType>

  <simpleType name="portsEnum">
    <restriction base="string">
      <enumeration value="USB"/>
      <enumeration value="COM"/>
      <enumeration value="LPT"/>
    </restriction>
  </simpleType>


  <complexType name="hardwareType">
    <sequence>
      <element type="boolean" name="keyboard"/>
      <element type="boolean" name="mouse"/>
      <element type="boolean" name="speakers"/>
    </sequence>
  </complexType>


</schema>

=== orangeStas/WebProjectWithXML/src/resources/Devices.xml
<?xml version="1.0" encoding="utf-8"?>
<dev:computers xmlns:dev="http://127.0.0.1/device"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://127.0.0.1/schema Devices.xsd">

    <computer id="ID-1" name="Asus N56JK" origin="USA" price="745">
        <type>
            <peripheral>true</peripheral>
            <power>745</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>true</mouse>
                <speakers>false</speakers>
            </hardware>
            <ports>USB COM</ports>
        </type>
        <critical>true</critical>
    </computer>

    <computer id="ID-2" name="HP Pavilion" origin="China" price="500">
        <type>
            <peripheral>false</peripheral>
            <power>400</power>
            <hardware>
                <keyboard>false</keyboard>
                <mouse>true</mouse>
                <speakers>false</speakers>
            </hardware>
            <ports>USB</ports>
        </type>
        <critical>false</critical>
    </computer>

    <computer id="ID-3" name="Dell" origin="USA" price="550">
        <type>
            <peripheral>true</peripheral>
            <power>745</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>false</mouse>
                <speakers>false</speakers>
            </hardware>
            <ports>USB COM LPT</ports>
        </type>
        <critical>false</critical>
    </computer>

    <computer id="ID-4" name="MSI M9h" origin="USA" price="400">
        <type>
            <peripheral>true</peripheral>
            <power>600</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>true</mouse>
                <speakers>true</speakers>
            </hardware>
            <ports>LPT</ports>
        </type>
        <critical>true</critical>
    </computer>

    <computer id="ID-5" name="MacBook" origin="USA" price="1000">
        <type>
            <peripheral>true</peripheral>
            <power>400</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>true</mouse>
                <speakers>false</speakers>
            </hardware>
            <ports>USB</ports>
        </type>
        <critical>true</critical>
    </computer>

    <computer id="ID-6" name="iMac" origin="USA" price="1300">
        <type>
            <peripheral>true</peripheral>
            <power>700</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>true</mouse>
                <speakers>true</speakers>
            </hardware>
            <ports>USB COM LPT</ports>
        </type>
        <critical>true</critical>
    </computer>

    <computer id="ID-7" name="LG gv5" origin="China" price="400">
        <type>
            <peripheral>false</peripheral>
            <power>500</power>
            <hardware>
                <keyboard>false</keyboard>
                <mouse>false</mouse>
                <speakers>false</speakers>
            </hardware>
            <ports>COM</ports>
        </type>
        <critical>false</critical>
    </computer>

    <computer id="ID-8" name="ACER Aspire" origin="USA" price="440">
        <type>
            <peripheral>true</peripheral>
            <power>300</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>false</mouse>
                <speakers>false</speakers>
            </hardware>
            <ports>COM LPT</ports>
        </type>
        <critical>true</critical>
    </computer>

    <computer id="ID-9" name="Lenovo hg21" origin="China" price="200">
        <type>
            <peripheral>true</peripheral>
            <power>300</power>
            <hardware>
                <keyboard>false</keyboard>
                <mouse>true</mouse>
                <speakers>false</speakers>
            </hardware>
            <ports>USB</ports>
        </type>
        <critical>false</critical>
    </computer>

    <computer id="ID-10" name="SAMSUNG LT213" origin="Korea" price="490">
        <type>
            <peripheral>false</peripheral>
            <power>400</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>true</mouse>
                <speakers>true</speakers>
            </hardware>
            <ports>USB</ports>
        </type>
        <critical>true</critical>
    </computer>

    <computer id="ID-11" name="ASUS ZenBook" origin="China" price="800">
        <type>
            <peripheral>true</peripheral>
            <power>370</power>
            <hardware>
                <keyboard>true</keyboard>
                <mouse>false</mouse>
                <speakers>true</speakers>
            </hardware>
            <ports>USB COM LPT</ports>
        </type>
        <critical>true</critical>
    </computer>
</dev:computers>
